version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"
packages: [php8.1-curl, php8.1-http, php8.1-raphf, php8.1-xml]


command:
  build:
    - "composer update"

  test:
    - "vendor/bin/phpunit --verbose --testdox tests/"
